country: china
province: shanghai
city: shanghai
area: putong

port: 8080

user:
  name: xiaoliu
  age: 32
  hoppy:
   - sleep
   - game

datasource:
  url: jdbc:mysql://localhost:3307/cloud_note?&useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
  name: spring
  password: 123456
  driver: com.mysql.cj.jdbc.Driver

server:
  port: 80
  servlet:
    context-path: /love